bingTranslation:
  subscriptionKey: replace_with_your_client_id
chatLogging:
  file:
    enabled: true
  logentries:
    enabled: false
    token: replace_with_your_logentries_log_token
    debug: false
whisper:
  radius: 10