name: Tongues
main: org.gamesforpeace.tongues.TonguesPlugin
version: 0.7.0
description: Tongues implements real time translation support for messages between players. Currently Chat and Whisper messages are supported.

commands:
  tongues.setlang:
    description: Setup the language used for translation of messages sent to the player.
    permission: tongues.setlang
    aliases: [lang, setlang]
    usage: |
      /<command> [language]
      When [language] is "?" the current setup language is displayed. When "none" is specified, language setup is cleared.
      Or
      /<command> [player] [language]
      When a player name is specified, the command operates similarly, on another player. (This command can also be invoked from a non player)
  tongues.whisper:
    description: Whisper a message to nearby players
    permission: tongues.whisper
    aliases: whisper
    usage: /<command> <message>

permissions:
  tongues.setlang:
    description: Allows a player to setup/query his language
    default: true
  tongues.setlang.others:
    description: Allows to setup/query other player's language
    default: op
    children:
      tongues.setlange: true
  tongues.whisper:
    description: Allows to whisper a message to other players nearby
    default: true
     