name: Tongues
main: org.gamesforpeace.tongues.TonguesPlugin
version: 1.4.0
description: Tongues implements real time translation support for messages between players. Currently Chat and Whisper messages are supported.

commands:
  tongues.setlang:
    description: Setup the language used for translation of messages sent to the player.
    permission: tongues.setlang
    aliases: [lang, setlang]
    usage: |
      /<command> [language]
      When [language] is "?" the current setup language is displayed. When "none" is specified, language setup is cleared.
      Or
      /<command> [player] [language]
      When a player name is specified, the command operates similarly, on another player. (This command can also be invoked from a non player)
  tongues.whisper:
    description: Whisper a message to nearby players
    permission: tongues.whisper
    aliases: whisper
    usage: /<command> <message>
  tongues.talk:
    description: Talks to other players in various ways
    permission: tongues.talk
    aliases: [talk, t]
    usage: |
      /<command> <message>
      Will whisper the message to any players around you
      /<command> <player name> <message>
      Will send the message only to the specified player
      /<command> <group name> <message>
      Will send the message only to players within that specified group
      /<command> * <message>
      Will send the message to all players
  tongues.listen:
    description: Toggles listening to all chat communications on the server on/off
    permission: tongues.listen
    aliases: [listen, tl]
    usage: |
      /<command> on
      Enables global chat listen (including whispers and translations)
      /<command> off
      Enables global chat listen (including whispers and translations)
  tongues.groups:
    description: Manages the chat groups.
    permission: tounges.groups
    aliases: [tg]
    usage: |
      /<command> add <group name> <player UUID>
      Adds a player to a group (creates the group if it does not exist)
      /<command> add * <player UUID>
      Adds a player to all existing groups
      /<command> remove <group name> <player UUID>
      Removes a player from a group (delete the group if it becomes empty)
      /<command> remove * <player UUID>
      Removes a player from all group (delete the groups if they become empty)
      /<command> remove <group name> *
      Removes all players from a group (delete the group)
      /<command> remove * *
      Removes all players from all group (deletes all groups)
      /<command> list
      Not yet supported
      /<command> list <group name>
      Not yet supported
      /<command> list * <player UUID>
      Not yet supported
      /<command> save
      Not yet supported
      /<command> reload
      Not yet supported

permissions:
  tongues.setlang:
    description: Allows a player to setup/query his language
    default: true
  tongues.setlang.others:
    description: Allows to setup/query other player's language
    default: op
    children:
      tongues.setlange: true
  tongues.whisper:
    description: Allows to whisper a message to other players nearby
    default: true
  tongues.talk:
    description: Allows to talk to players in a group or talk to a specific player
    default: true
    children:
      tongues.whisper: true
  tongues.talk.all:
    description: Allows to talk to any player
    default: op
    children:
      tongues.talk: true
  tongues.listen:
    description: Allows listening to any chat on the server
    default: op
  tounges.groups:
    description: Allows managing the chat groups
    default: op